; PlatformIO Project Configuration File
; ESP32-C3 Super Mini 温湿度气象站
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitc-02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
monitor_speed = 115200
; 启用 USB CDC，烧录/串口监控走板载 USB
board_build.arduino.usb_cdc_on_boot = enable

lib_deps =
    majicdesigns/MD_MAX72XX @ ^3.5.0
    majicdesigns/MD_Parola @ ^3.6.0
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    knolleary/PubSubClient @ ^2.8
